### PR TITLE
Fix deployments

### PR DESCRIPTION
**Pull request by Gundersanne**
TODO:
- [x] make sure the devel container still works.

### CODE REVIEW

**Comment by Gundersanne** [comment]
I ran it locally with both podman-compose and docker-compose, so should be good I think :)

**Comment by Gundersanne** [comment]
@ochosi if you wanna check this out if it's easier to run it now. If you feel like trying out the compose file in the devel/ dir that would be great too :)

**Comment by ochosi** [comment]
Nice work - the deployment works neatly now! (tested with proxy 3.2.2)

**Comment by teg** [comment]
Looks nice!

Regarding the dockerfile: I think this will make the caching worse, if I understand correctly: the npm install will now be re run on every change to the working directory

**Comment by Gundersanne** [comment]
> Looks nice!
> 
> Regarding the dockerfile: I think this will make the caching worse, if I understand correctly: the npm install will now be re run on every change to the working directory

Ah! I didn't think of that, i'll revert that change

**Review by teg — APPROVED** [review]

**Pull request merged**
