### PR TITLE
Devel improvements

### PR DESCRIPTION
**Pull request by Gundersanne**

### CODE REVIEW

**Review by teg — COMMENTED** [review]
Nice!

**Review by teg — APPROVED** [review]

**Comment by Gundersanne** [comment]
I wanna test this some more on a vm before merging

**Comment by teg** [comment]
Ehm.... sorry! I seem to have ignored your label and comment :-/

**Comment by Gundersanne** [comment]
probably should've opened it as a draft anyway :)

**Comment by teg** [comment]
> probably should've opened it as a draft anyway :)

You know me and green buttons... I can't be trusted with them...

**Pull request merged**
