### PR TITLE
CreateImageWizard: sort packages by relevance

### LINKED ISSUE #256: packages: ordering search results
A big improvement can be made here. When searching for `vi` for instance, the packages get listed in alphabetical order, and anything that contains `vi` gets listed.

1. List exact matches first
2. Then list packages that start with the entered letters

And I think case insensitive would be best here.

### PR DESCRIPTION
**Pull request by kingsleyzissou**
Sort the package results in the CreateImageWizard first by exact matches and then by package results
that start with the same letters as the search term. Fixes #256

Before (search term: "libvirt"):

before_packages

After:
after_packages

### CODE REVIEW

**Review by jkozol — CHANGES_REQUESTED** [review]
This works great when sorting on package load. But, if I move packages to the chosen list and then back to the available list they are added to the bottom of the list. Could you also add this sort to the moveSelected and moveAll functions when packages are added back to the available packages list?

**Comment by kingsleyzissou** [comment]
Thanks for the review. Yeah of course I can add the sort to those functions

**Comment by kingsleyzissou** [comment]
@jkozol I added in some tests to check that now too and improved the sort a little bit, because it wasn't really sorting the relevant results alphabetically.

**Review by jkozol — APPROVED** [review]
Thanks for this. Looks good to me!! Sorting works great :)

**Pull request merged**
