### PR TITLE
CreateImageWizard: rhc support

### PR DESCRIPTION
**Pull request by croissanne**
[1-2023-03-07_12.35.05.webm](https://user-images.githubusercontent.com/11140201/223412019-7ac627eb-67c2-4b20-a167-56f553bc73fd.webm)

### CODE REVIEW

**Comment by jrusz** [comment]
@croissanne can you resolve the conflict please? It won't build the image otherwise, the old one is gone already and I'd like to take a look at testing this.

**Comment by jrusz** [comment]
Ok so like I thought, since we skip registration this is not actually breaking our testing as that option has not changed. I will figure out how to add testing for this though.

**Comment by croissanne** [comment]
Ah this will need a small IQE change, as the title changed from "Registration" to "Register".

**Comment by croissanne** [comment]
With https://github.com/RedHatInsights/image-builder-frontend/pull/988 the review styling will be easier to get closer to the designs. The list spacing is much closer to the current spacing.

**Comment by regexowl** [comment]
The `Show additional connection options` seems to get stuck as disabled when you 
- open it
- uncheck one or both checkboxes
- click on `Register later`
- and back on `Automatically register and enable advanced capabilities`

**Comment by croissanne** [comment]
> The `Show additional connection options` seems to get stuck as disabled when you
> 
>     * open it
> 
>     * uncheck one or both checkboxes
> 
>     * click on `Register later`
> 
>     * and back on `Automatically register and enable advanced capabilities`

eep, i'll take a look.

**Comment by croissanne** [comment]
> Went through the rest and I'd say otherwise it looks good! +1
> 
> One question about the mocks - should there be the updated text for Register later and the org ID in the activation popover? I think the mocks were still being worked on so I'm not sure if there were any changes I'm just not aware of

So the mockups don't have any text for the popovers, so I just came up with something myself. Happy to discuss those  amongst us, but I don't want to block anymore on any outside input.

**Comment by regexowl** [comment]
> > Went through the rest and I'd say otherwise it looks good! +1
> > One question about the mocks - should there be the updated text for Register later and the org ID in the activation popover? I think the mocks were still being worked on so I'm not sure if there were any changes I'm just not aware of
> 
> So the mockups don't have any text for the popovers, so I just came up with something myself. Happy to discuss those amongst us, but I don't want to block anymore on any outside input.

Right, I remember that being mentioned on the meeting. The texts for the popovers look good.
I was thinking these ones:
Screenshot from 2023-03-07 16-40-30

But the copy can be updated later, just wanted to check

**Comment by croissanne** [comment]
> > > Went through the rest and I'd say otherwise it looks good! +1
> > > One question about the mocks - should there be the updated text for Register later and the org ID in the activation popover? I think the mocks were still being worked on so I'm not sure if there were any changes I'm just not aware of
> > 
> > 
> > So the mockups don't have any text for the popovers, so I just came up with something myself. Happy to discuss those amongst us, but I don't want to block anymore on any outside input.
> 
> Right, I remember that being mentioned on the meeting. The texts for the popovers look good. I was thinking these ones: Screenshot from 2023-03-07 16-40-30
> 
Can definitely add those!

**Review by regexowl — APPROVED** [review]
Nice! LGTM :)

**Comment by kaedward** [comment]
I see this is merged already, but I was asked to review the popovers here. I'll go ahead and leave this info here in case there are future updates planned.

I have a few suggestions for changes, which include making the "read more" links a little more descriptive, and avoiding using acronyms where possible. Here are the suggested contents:

**About Red Hat Subscription Management**
Registered systems are entitled to support services, errata, patches, and upgrades.
Learn more about Red Hat Subscription Management

**About Red Hat Insights**
Red Hat Insights client provides actionable intelligence about your Red Hat Enterprise Linux environments, helping to identify and address operational and vulnerability risks before an issue results in downtime. 
Learn more about Red Hat Insights

**About Remote Host Configuration (RHC)**
RHC allows Red Hat Enterprise Linux hosts to connect to Red Hat Insights. RHC is required to use the Red Hat Insights Remediations service.
Learn more about Remote Host Configuration

Please let me know if you have any questions/comments about any of these changes, or if you'd like a content review of the rest of the UI shown in this issue :-)

**Comment by croissanne** [comment]
Created a followup in #997 to update the tooltips.

**Comment by arburka** [comment]
@kaedward thank you for the input!

**Pull request merged**
