### PR TITLE
api/imageBuilder: update imageBuilder schema for blueprints changes

### PR DESCRIPTION
**Pull request by amirfefer**

### CODE REVIEW

**Comment by regexowl** [comment]
There seems to be a bunch of comments removed manually in `imageBuilderApi.ts`, could you please update the file by running `npm run api`? That should re-generate the code based on the schema.

**Comment by lucasgarfield** [comment]
I wonder if the default change to `@rtk-query/codegen-openapi` was changed, because when I run `npm run api` on my machine it removes comments from *all* API files.

**Comment by amirfefer** [comment]
@regexowl, I didn't change anything manually, just copy pasted the new schema and run the openapi generator  script.

**Comment by lucasgarfield** [comment]
superseded by #1580

**Pull request closed without merging**
