### PR TITLE
HMS-2782: Expose OCI in the Wizard

### PR DESCRIPTION
**Pull request by regexowl**
This exposes the option to create OCI images in the Wizard. The feature is available only for Preview for now.

I've also added mock fixtures for an OCI image to have an example of how the data are displayed.

### CODE REVIEW

**Review by lavocatt — APPROVED** [review]
Amazing work! Ship it :rocket:

**Review by croissanne — COMMENTED** [review]
I like it, can we make the popover wider though? Think it'll be more readable.

image

**Comment by regexowl** [comment]
For sure! Like this?

Screenshot from 2023-10-23 14-27-56

**Review by croissanne — COMMENTED** [review]
Oh also, the pre-authenticated requests expire after 7 days.

**Comment by regexowl** [comment]
> Oh also, the pre-authenticated requests expire after 7 days.

Ah, okay. Do we want to show the Expired status and "Recreate image" after the 7 days? With the "Expiring in x days" countdown, similar to s3 targets?

**Comment by croissanne** [comment]
> > Oh also, the pre-authenticated requests expire after 7 days.
> 
> Ah, okay. Do we want to show the Expired status and "Recreate image" after the 7 days? With the "Expiring in x days" countdown, similar to s3 targets?

yea I think so.

**Comment by regexowl** [comment]
Alright, this should do the trick. Expiring status added :timer_clock:

**Review by croissanne — APPROVED** [review]
thank you!

**Comment by teg** [comment]
Question (for a follow-up): Could referring to "OCI images" lead to confusion between:
- [Open Container Initiative](https://opencontainers.org), and
- [Oracle Cloud Infrastructure](https://go.oracle.com)
People already think image builder builds container images, and hopefully one day we will...

**Comment by croissanne** [comment]
> Question (for a follow-up): Could referring to "OCI images" lead to confusion between:
> 
>     * [Open Container Initiative](https://opencontainers.org), and
> 
>     * [Oracle Cloud Infrastructure](https://go.oracle.com)
>       People already think image builder builds container images, and hopefully one day we will...

image
in the UI it's spelled out fully, so I think it should be ok?

**Pull request merged**
