### PR TITLE
Launch button in stable environments

### PR DESCRIPTION
**Pull request by ezr-ondrej**
This moves Beta only features to stable environment:
- Sharing Images through Sources
- Launch button

This tries to avoid any refactoring, just moving components from Beta to stable with minimal changes.

@lucasgarfield @croissanne I guess this shoul go first, once we agree on going GA, I'll prepare follow-ups for the banners, but wanted to agree on this ahead of time, so we just click the button on GA date :)

Refs https://issues.redhat.com/browse/HMS-2353

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
Fixed most of the tests, still missing few :)

**Comment by ezr-ondrej** [comment]
:green_apple: :tada:

**Comment by ezr-ondrej** [comment]
/retest
content sources [fails to deploy](https://ci.int.devshift.net/job/RedHatInsights-image-builder-frontend-pr-check/1450/console) :face_exhaling:

**Comment by lucasgarfield** [comment]
I'm ready to approve this once we can get the IQE tests working (or even without IQE tests passing if we can get approval from QE).

**Comment by jrusz** [comment]
> I'm ready to approve this once we can get the IQE tests working (or even without IQE tests passing if we can get approval from QE).

Should be fine to merge, content-sources are failing to deploy again, I'll do some investigation on the side.

**Review by lucasgarfield — APPROVED** [review]
Looks good to me, nice work Ondrej!

**Pull request merged**
