### PR TITLE
Remove embedded quickstarts & Preview

### PR DESCRIPTION
**Pull request by shaded-enmity**
With our quickstarts now merged to prod we can
start using the quickstart API to invoke them.
Also change all Beta user facing text to Preview

### CODE REVIEW

**Review by croissanne — DISMISSED** [review]

**Comment by shaded-enmity** [comment]
hey @regexowl I noticed you were making some changes around this code in #1108 - can you ping me once that is merged so that I can rebase?

@lucasgarfield I remember we talked about updating the links in the upstream quickstarts, is that something you're working on?

**Comment by jkozol** [comment]
https://github.com/RedHatInsights/quickstarts/pull/92 has been merged and https://github.com/RedHatInsights/image-builder-frontend/pull/1108 has been acked. Is this good to go @croissanne @shaded-enmity ?

**Comment by regexowl** [comment]
@shaded-enmity #1108 has been merged

**Comment by shaded-enmity** [comment]
@regexowl @jkozol @croissanne thanks for the headsup! I just rebased so we should be good to go

**Review by jkozol — APPROVED** [review]

**Pull request merged**
