### PR TITLE
test: Replace `.getBy` queries by awaited `.findBy`

### PR DESCRIPTION
**Pull request by regexowl**
Components sometimes render slower than tests run which causes failures when the test suite expects elements that did not finish their rendering yet.

This should help to prevent most of possible problems with the rendering speed.

### CODE REVIEW

**Review by mgold1234 — APPROVED** [review]
/lgtm

**Comment by regexowl** [comment]
Had to resolve some conflicts and rebase, the PR should be ready for the review again

**Review by mgold1234 — APPROVED** [review]
/lgtm

**Review by mgold1234 — APPROVED** [review]
/lgtm

**Pull request merged**
