### PR TITLE
Provisioning only launch

### PR DESCRIPTION
**Pull request by ezr-ondrej**
~Depends on https://github.com/RHEnVision/provisioning-frontend/pull/238~

### CODE REVIEW

**Comment by croissanne** [comment]
We need to be sure that also for the link, we can select a region. Or show a link for each region. But this would be amazing <3

**Comment by ezr-ondrej** [comment]
You're right, I've missed that, but we can easily add the region select to the empty state :)

**Comment by ezr-ondrej** [comment]
The empty state just got merged, I believe this is ready to go in? :)

**Comment by lucasgarfield** [comment]
Absolutely love this! I can't wait until the Launch Wizard is in production and we can just get rid of our old launch popover completely.

**Review by lucasgarfield — APPROVED** [review]
Thank you!

**Pull request merged**
