### PR TITLE
ImagesTable: Update ClonesTable

### PR DESCRIPTION
**Pull request by regexowl**
This updates ClonesTable according to the new mocks.

### CODE REVIEW

**Comment by regexowl** [comment]
Question regarding the AMIs - are those the same as UUID of the AWS clones?

**Comment by lucasgarfield** [comment]
> Question regarding the AMIs - are those the same as UUID of the AWS clones?

No, the AMI is different than the UUID for the clones (and their parent composes, too). If you use the `selectCloneById` selector from the `clonesSlice` it has an `ami` property you can use to get the ami. :smile:

**Comment by lucasgarfield** [comment]
This looks really great! I wish we could ensure that the column alignment was consistent. For instance, if you have two AWS images expanded the resulting output is a bit jarring:

image

I brought this up in a design meeting once and there was some discussion about the drawbacks of fixing column widths. I think we can merge this for now (nice work!) and implement a solution for consistent column locations in a future PR.

**Comment by lucasgarfield** [comment]
Had a chat with @arburka about column widths. The solution actually ended up being a lot easier than I thought it would be to implement, so I say we put it in this PR.

image
image

**Comment by regexowl** [comment]
Amazing! Thanks a lot @lucasgarfield 
I've updated the PR to include the column widths.

**Comment by lucasgarfield** [comment]
Love it! Thanks!

**Review by lucasgarfield — APPROVED** [review]

**Comment by regexowl** [comment]
Oh no :scream_cat: created a revert PR

**Comment by jrusz** [comment]
> Oh no scream_cat created a revert PR

Thank you :) ... We really need to coordinate better on breaking changes

**Pull request merged**
