### PR TITLE
API: improve api.sh and update api

### PR DESCRIPTION
**Pull request by lucasgarfield**
First commit modifies `api.sh` so that the image builder api.yaml file is downloaded with curl, this way we don't have to manually download it anymore.

Second commit updates api via `npm run api`.

### CODE REVIEW

**Review by regexowl — APPROVED** [review]
Amazing, thank you! :star_struck:

**Review by ezr-ondrej — APPROVED** [review]
Might be great to download all other specs as well, but it might be a bit slow then and we might want to have separate actions for it and this is a perfect start :+1: 

BTW the failure is "expected" and is being worked on by QE (in Content Sources channel)

**Comment by ezr-ondrej** [comment]
Ah... there is a bit of an issue now, that `npm run api` is run in the CI to verify the API was not tempered with manually, which means that anytime the backend updates api spce, all fronted PR checks fail :)

I'll propose a split of the actions to `npm run api:update` that would download and regen and `npm run api` that would only regen :)
Tomorrow tho, I'm just stopping by today xD

**Comment by regexowl** [comment]
> Ah... there is a bit of an issue now, that `npm run api` is run in the CI to verify the API was not tempered with manually, which means that anytime the backend updates api spce, all fronted PR checks fail :)
> 
> I'll propose a split of the actions to `npm run api:update` that would download and regen and `npm run api` that would only regen :) Tomorrow tho 😛

Oof :dizzy_face: great catch! Splitting the actions into two steps sounds great. :+1:

**Comment by ezr-ondrej** [comment]
> Splitting the actions into two steps sounds great. 👍

Here we go: https://github.com/RedHatInsights/image-builder-frontend/pull/1585 :)

**Pull request merged**
