### PR TITLE
Content sources

### PR DESCRIPTION
**Pull request by lucasgarfield**
Adds support for Content Sources.

### CODE REVIEW

**Comment by jkozol** [comment]
Screenshot from 2022-12-22 16-11-58

I don't think we should list the rhel subscriptions as third party.

**Comment by jkozol** [comment]
Screenshot from 2022-12-22 16-17-09

If packages are selected and then the third party sources are removed should we remove the packages from third party?

**Comment by croissanne** [comment]
> Screenshot from 2022-12-22 16-11-58
> 
> I don't think we should list the rhel subscriptions as third party.

Did you define these yourself in settings/content?

**Review by croissanne — APPROVED** [review]

**Comment by croissanne** [comment]
Amazing, let's hold off on merging until next year though :) Thank you <3

**Comment by lucasgarfield** [comment]
> Screenshot from 2022-12-22 16-17-09
> 
> If packages are selected and then the third party sources are removed should we remove the packages from third party?

This is tricky. Neither image-builder nor osbuild-composer actually maps packages to a specific repository. The request schema (and therefore the JSON blob we work with) has a field for package names, and a field for repositories (under payload.customizations). So while it would be a nice feature to have, it is not straightforward to implement.

**Comment by lucasgarfield** [comment]
> Screenshot from 2022-12-22 16-11-58
> 
> I don't think we should list the rhel subscriptions as third party.

This will be fixed by #894

**Pull request merged**
