### PR TITLE
CreateImageWizard: don't allow arbitrary mountpoints under /boot

### PR DESCRIPTION
**Pull request by croissanne**
afbeelding

### CODE REVIEW

**Comment by lucasgarfield** [comment]
@croissanne can you please re-do the PR description, I think the image failed to upload when you created it :sweat_smile:

**Review by lucasgarfield — APPROVED** [review]
LGTM!

**Comment by lucasgarfield** [comment]
Linting failed:
`  79:27  error    Replace `·prefix.startsWith("/boot"` with `prefix.startsWith('/boot'`                                                                                                                                                                                                                                       prettier/prettier`
Should be auto-fixable with `npm run lint:fix:js`

**Comment by croissanne** [comment]
> Linting failed: ` 79:27 error Replace`·prefix.startsWith("/boot"`with`prefix.startsWith('/boot'` prettier/prettier` Should be auto-fixable with `npm run lint:fix:js`

ah thanks, it's too late my brain is tired :seal:

**Review by lucasgarfield — APPROVED** [review]
lgtm!

**Pull request merged**
