### PR TITLE
CreateImageWizard: don't obscure activation key

### PR DESCRIPTION
**Pull request by chloenayon**
Activation key was previously obscured by stars, instead just show it
(both in the input and in the review step) as it isn't secret.

### CODE REVIEW

**Review by Gundersanne — DISMISSED** [review]
lgtm! thank you

**Review by jkozol — DISMISSED** [review]
Yay! Nice. Looks good :)

**Comment by jkozol** [comment]
Fixes #196

**Comment by jkozol** [comment]
@chloenayon Can you rebase on top of main?

**Review by jkozol — APPROVED** [review]

**Pull request merged**
