### PR TITLE
constants: Introduce RHEL_8 constant

### PR DESCRIPTION
**Pull request by Gundersanne**
Bump rhel-84 to rhel-85.

---

Ideally this would be part of #6 ; where we'd pick the latest rhel version that hte service supports dynamically, but this takes priority.

### CODE REVIEW

**Review by teg — COMMENTED** [review]
Thanks for this!

**Comment by Gundersanne** [comment]
@teg actually not correct, pushing a fix

**Comment by teg** [comment]
Notice my foresight in realising I was not competent enough to approve.

**Review by jkozol — APPROVED** [review]
I cannot currently verify a successful image build but this looks correct to me and the POSTed compose object is as expected

**Pull request merged**
