### PR TITLE
ImagesTable: Add image details and update ClonesTable

### PR DESCRIPTION
**Pull request by regexowl**
This adds expandable rows details for each image and updates ClonesTable according to the new [mocks](https://www.sketch.com/s/d7aa6d29-fca0-4283-a846-09cc5fd10612/a/qbbyGg3).

### CODE REVIEW

**Comment by regexowl** [comment]
:wave: @jrusz 
Here's the PR with both changes to the clones table (included in the reverted https://github.com/RedHatInsights/image-builder-frontend/pull/1097) and the updated image details

**Comment by jrusz** [comment]
> wave @jrusz Here's the PR with both changes to the clones table (included in the reverted #1097) and the updated image details

Thank you! I'll work on adjusting the test suite right away.

**Comment by jrusz** [comment]
Hi @regexowl is the `Source` supposed to be the ID or the name of it? From what I can see it shows the ID but in the sketch I saw a name... 
image

**Comment by lucasgarfield** [comment]
> Hi @regexowl is the `Source` supposed to be the ID or the name of it? From what I can see it shows the ID but in the sketch I saw a name... image

@jrusz, for now let's assume that the name should be displayed. The source id is only used internally. We will just need to update the code in this PR so that we resolve the name from the id before displaying it.

**Comment by regexowl** [comment]
Hey @jrusz, the Source is indeed supposed to show the name of the source. I'll update the code. Thank you for letting me know about this!

**Comment by regexowl** [comment]
Displaying of the source name is fixed!

@jrusz We will be ready to merge after the review, would that be alright from your side?

**Comment by jrusz** [comment]
> Displaying of the source name is fixed!
> 
> @jrusz We will be ready to merge after the review, would that be alright from your side?

Yeah go ahead, there are unrelated issues in ephemeral so I won't make it work now. Thanks for letting me know!

**Comment by jrusz** [comment]
I may have found another issue. There is no information shown when the image build is done via API, is that expected? The following two images are pretty much the same, the UI one is still building though.
image

**Comment by regexowl** [comment]
Alright, this should do the trick. Thanks a lot! Those were great points :+1:

**Review by lucasgarfield — APPROVED** [review]
Looks great!

**Pull request merged**
