### PR TITLE
Wizard/test: Remove unused variables

### PR DESCRIPTION
**Pull request by regexowl**
This removes unused variable from the code.

### CODE REVIEW

**Review by lucasgarfield — APPROVED** [review]
lgtm

**Comment by lucasgarfield** [comment]
Hm, it is odd that the Travis test flaked. It is the "Click through all steps with valid values" test that failed, it received an empty object instead of the proper requests.

**Comment by regexowl** [comment]
> Hm, it is odd that the Travis test flaked. It is the "Click through all steps with valid values" test that failed, it received an empty object instead of the proper requests.

Weird. The re-run worked, so could have been really just a flake. I'll merge this PR, but will keep an eye on similar errors in the future.

**Pull request merged**
